<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Register your application on <a href="http://openweathermap.org/api" target="_blank">openweathermap.org</a> and obtain your API key.' => 'Registriere deine Anwendung unter <a href="http://openweathermap.org/api" target="_blank">openweathermap.org</a> und erhalte einen API Schlüssel.',
    'Display temperature' => 'Anzeige Temperatur',
    '<strong>Weather Widget</strong> configuration' => '<strong>Wetter Widget</strong> Einstellungen',
    'Enter city like "Berlin, Germany"' => 'Gebe eine Stadt ein z.B. "Berlin, Germany"',
    'Fahrenheit' => 'Fahrenheit',
    'Humidity:' => 'Feuchtigkeit',
    'Kelvin' => 'Kelvin',
    'OpenWeatherMap API Key' => 'OpenWeatherMap API Schlüssel',
    'Unit for temperature' => 'Einheit für Temperatur',
    'Unit for windspeed' => 'Einheit für Windgeschwindigkeit',
    'Wind:' => 'Wind:',
];
